### ISSUE TITLE
Chapter 3

### ISSUE THREAD

**Issue by KewTeacher** [Taneil-Kew/Chapter-2-4#4]
1. "we like turltes.py" it should print out on separate lines. Try using a loop
3. "months.py" only prints out for 3 months
5: only 5c is completed

missing the rest of 5, all of 6,7,8,11 and 12

Assignment was: Exercises 1,3,5,6,7,8,11,12 - You may substitute a creative turtle drawing for 11 or 12

**Comment by KewTeacher** [comment]
5a has error:

 ```
File "C:\Users\Admin\Documents\GitHub\taneil\Chapter-2-4\a5.py", line 2
    foor i in xs:
         ^
SyntaxError: invalid syntax
```

**Comment by KewTeacher** [comment]
5c should print out the sum of the numbers in the list

**Comment by KewTeacher** [comment]
5d should print out the product of all the numbers in the list at the end

**Comment by KewTeacher** [comment]
All #5 exercises seem to be using the wrong list of numbers. It should use: xs = [12, 10, 32, 3, 66, 17, 42, 99, 20]

**Comment by KewTeacher** [comment]
6a error:
```
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\GitHub\taneil\Chapter-2-4\a6.py", line 2, in <module>
    wn=turtle.screen()
AttributeError: module 'turtle' has no attribute 'screen'
```

**Comment by KewTeacher** [comment]
6c has the error:
```
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\GitHub\taneil\Chapter-2-4\c6.py", line 2, in <module>
    wn=turtle.screen()
AttributeError: module 'turtle' has no attribute 'screen'
```

**Comment by KewTeacher** [comment]
7 has error:
```
 File "C:\Users\Admin\Documents\GitHub\taneil\Chapter-2-4\7.py", line 4
    steps=[8352,86,94,42,16,954,32,08,50,460]
                                    ^
SyntaxError: invalid token
```

**Comment by KewTeacher** [comment]
8 has the issue:
```
 File "C:\Users\Admin\Documents\GitHub\taneil\Chapter-2-4\8.py", line 5
    steps=[8352,86,94,42,16,954,32,08,50,460]
                                    ^
SyntaxError: invalid token
```

**Comment by KewTeacher** [comment]
11 and 12 are still missing

**Comment by KewTeacher** [comment]
In general, you should test your programs yourself before pushing to github.
